In [ ]:
from master_llm import MasterLLM
from master_tokenizer import MasterTokenizer
import torch
import torch.nn as nn

In [2]:
u_tokenizer = MasterTokenizer("tokenizer.json")

prompt = "the capital of united"

tokens = u_tokenizer.encode(prompt)

In [ ]:
torch.manual_seed(1)

u_model = MasterLLM(vocab_size=len(u_tokenizer.vocab), embedding_dim=4, num_heads=2, context_length=32, num_layers=3)

tokens = tokens.unsqueeze(0)

out = u_model(tokens)

out.shape

torch.Size([1, 7, 64])

input: [A, B, C]

target: [B, C, D]

In [8]:
probs = torch.softmax(out[-1], dim=-1)
max_prob, max_index = torch.max(probs, dim=-1)
max_prob, max_index, probs

(tensor([0.0869, 0.0544, 0.0759, 0.0417, 0.0474, 0.0454, 0.0916],
        grad_fn=<MaxBackward0>),
 tensor([ 7,  0,  7,  0,  0,  0, 60]),
 tensor([[0.0678, 0.0212, 0.0026, 0.0033, 0.0060, 0.0076, 0.0482, 0.0869, 0.0018,
          0.0045, 0.0035, 0.0044, 0.0151, 0.0288, 0.0033, 0.0055, 0.0021, 0.0094,
          0.0299, 0.0040, 0.0172, 0.0016, 0.0014, 0.0046, 0.0253, 0.0021, 0.0021,
          0.0068, 0.0116, 0.0012, 0.0103, 0.0038, 0.0004, 0.0120, 0.0005, 0.0024,
          0.0338, 0.0098, 0.0098, 0.0326, 0.0676, 0.0047, 0.0105, 0.0250, 0.0041,
          0.0321, 0.0011, 0.0144, 0.0299, 0.0082, 0.0324, 0.0017, 0.0402, 0.0188,
          0.0009, 0.0106, 0.0009, 0.0115, 0.0032, 0.0476, 0.0629, 0.0224, 0.0033,
          0.0010],
         [0.0544, 0.0253, 0.0077, 0.0067, 0.0106, 0.0117, 0.0363, 0.0440, 0.0052,
          0.0058, 0.0082, 0.0082, 0.0107, 0.0295, 0.0097, 0.0106, 0.0056, 0.0120,
          0.0176, 0.0101, 0.0144, 0.0060, 0.0051, 0.0103, 0.0374, 0.0051, 0.0043,
          0.0132, 0.012