RESIDUAL BAĞLANTI DECODER

In [ ]:
from master_llm import MasterLLM
from master_tokenizer import MasterTokenizer
import torch
import torch.nn as nn

In [ ]:
u_tokenizer = MasterTokenizer("tokenizer.json")

prompt = "the capital of united"

tokens = u_tokenizer.encode(prompt)

In [ ]:
torch.manual_seed(1)

u_model = MasterLLM(vocab_size=len(u_tokenizer.vocab), embedding_dim=4, num_heads=2, context_length=32)

sentence_meanings_with_attention_context = u_model(tokens)

sentence_meanings_with_attention_context

tensor([[-0.0790,  0.3310, -0.0789, -0.1503],
        [-0.0639,  0.3029, -0.0409, -0.0925],
        [-0.0537,  0.2982, -0.0362, -0.1277],
        [-0.0480,  0.2886, -0.0239, -0.1126],
        [-0.0472,  0.2827, -0.0158, -0.0909],
        [-0.0472,  0.2800, -0.0122, -0.0811],
        [-0.0493,  0.2787, -0.0103, -0.0693]], grad_fn=<AddmmBackward0>)

In [ ]:
from master_norm import MasterLayerNorm

norm_layer = MasterLayerNorm(embedding_dim=4)
norm_layer(sentence_meanings_with_attention_context)

tensor([[-0.4457,  1.7116, -0.4450, -0.8208],
        [-0.5618,  1.7208, -0.4189, -0.7401],
        [-0.4499,  1.6937, -0.3434, -0.9005],
        [-0.4776,  1.6937, -0.3220, -0.8941],
        [-0.5398,  1.7032, -0.3262, -0.8373],
        [-0.5718,  1.7069, -0.3276, -0.8075],
        [-0.6158,  1.7123, -0.3392, -0.7573]], grad_fn=<MulBackward0>)

![transformer-architecture](https://deeprevision.github.io/posts/001-transformer/transformer.png)

In [ ]:
# Load model directly
# from transformers import AutoTokenizer, AutoModelForCausalLM

# q_tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen3-0.6B")
# q_model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen3-0.6B")

![gelu](https://miro.medium.com/v2/resize:fit:1400/1*O5E-huBuY1UTHMmM--rhLQ.png)

In [ ]:
u_model

MasterLLM(
  (embedding): Embedding(64, 4)
  (pos_embedding): Embedding(32, 4)
  (self_attention): MasterCausalAttention(
    (q_weights): Linear(in_features=4, out_features=4, bias=False)
    (k_weights): Linear(in_features=4, out_features=4, bias=False)
    (v_weights): Linear(in_features=4, out_features=4, bias=False)
    (dropout): Dropout(p=0, inplace=False)
  )
  (norm): MasterLayerNorm()
  (MLP): MasterMLP(
    (gate_proj): Linear(in_features=4, out_features=16, bias=True)
    (up_proj): Linear(in_features=4, out_features=16, bias=True)
    (down_proj): Linear(in_features=16, out_features=4, bias=True)
    (gelu): GELU()
  )
)

In [ ]:
example_tensor = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]], dtype=torch.float32)
decoder_block = MasterDecoderBlock(embedding_dim=4, num_heads=2, context_length=3)
decoder_block(example_tensor)

tensor([[1.0732, 2.8224, 3.7446, 5.1143],
        [4.5839, 6.5470, 7.8686, 8.7928]], grad_fn=<AddBackward0>)