In [2]:
from master_llm import MasterLLM
from master_tokenizer import MasterTokenizer
import torch

In [3]:
u_tokenizer = MasterTokenizer("tokenizer.json")

prompt = "the capital of united states and the capital of france"

tokens = u_tokenizer.encode(prompt)

In [4]:
torch.manual_seed(1)

u_model = MasterLLM(vocab_size=len(u_tokenizer.vocab), embedding_dim=4, context_length=32)

sentence_meanings = u_model(tokens)

In [5]:
u_model

MasterLLM(
  (embedding): Embedding(64, 4)
  (pos_embedding): Embedding(32, 4)
)

In [6]:
from plot_tokens import plot_tokens

sentences = [
    {
        "words": sentence_meanings.detach().numpy(),
        "labels": u_tokenizer.tokenize(prompt),
        "color": "red", 
    }
]

In [7]:
plot_tokens(sentences, "Models Contex Space")

In [8]:
sentence_meanings

tensor([[-1.5256, -0.7502, -0.6540, -1.6095],
        [-0.2092, -0.2013, -0.7509, -0.0189],
        [ 0.9326, -0.2774,  0.3166, -1.6980],
        [ 0.7698, -0.1935,  0.1223, -0.0585],
        [-0.1228,  0.3777,  1.0470, -0.1133],
        [-0.4315, -0.1780,  0.6491, -0.0958],
        [-0.1496,  1.1284,  0.2814,  1.3386],
        [-0.4106, -0.1555, -0.6625, -0.1292],
        [-0.5907, -0.9515, -0.7913, -0.6940],
        [-0.3183,  1.2965, -0.8974, -0.5926],
        [ 0.5000, -0.1103,  0.5979, -0.1694],
        [-0.1583,  0.1584,  0.1103,  0.2478],
        [-0.7518, -0.0745,  0.2059, -0.1879],
        [-1.1096,  1.3501, -1.2345, -1.1534],
        [ 0.1257, -0.0357, -0.7692, -0.1990],
        [ 0.7132,  1.5620,  0.6792, -0.7215],
        [ 0.6472,  0.0046,  0.4344, -0.2021],
        [-0.5514,  0.2102,  0.8985,  0.3336],
        [-0.6643,  0.0446,  0.4077, -0.1972],
        [ 1.8345,  0.7552,  0.4377,  0.1818]], grad_fn=<CopySlices>)

In [9]:
# Pozisyon değerleri
the_pos = [-1.5256, -0.7502, -0.6540, -1.6095]
capital_pos = [0.9326, -0.2774,  0.3166, -1.6980]

In [10]:
# Farkların hesaplanması Manhattan distance ile
hardness_dist   = abs(the_pos[0] - capital_pos[0])
brightness_dist = abs(the_pos[1] - capital_pos[1])
redness_dist    = abs(the_pos[2] - capital_pos[2])
blueness_dist   = abs(the_pos[3] - capital_pos[3])

(hardness_dist, brightness_dist, redness_dist, blueness_dist)

(2.4582, 0.4728, 0.9706, 0.08850000000000002)

In [11]:
total_distance = (hardness_dist + brightness_dist + redness_dist  + blueness_dist) 
total_distance

3.9901

In [ ]:
apple = [-1.5256, -0.7502, -0.6540, -1.6095]
real_apple = [0.5, -0.5, -0.5, -1.5]

In [ ]:
# Farkların hesaplanması kosinüs benzerliği ile
from torch import dist

def is_apple(pos , real_pos):
    dist1 = pos[0] - real_pos[0]

    print("Distance from real apple:", dist1)

    if dist1 > 0:
        apple[0] -= 0.5
    
    else:
        apple[0] += 0.5

    return dist1 > 0 and dist1 < 0.5

is_apple(apple , real_apple)

Distance from real apple: -2.0256


False

In [14]:
apple = [-1.5256, -0.7502, -0.6540, -1.6095]
real_apple = [0.9326, -0.2774,  0.3166, -1.6980]

In [15]:
cos_sim_hardness = the_pos[0]*capital_pos[0] 
cos_sim_brightness = the_pos[1]*capital_pos[1] 
cos_sim_redness = the_pos[3]*capital_pos[3]

cos_sim_hardness, cos_sim_brightness, cos_sim_redness

total_distance = cos_sim_hardness + cos_sim_brightness + cos_sim_redness
total_distance

1.5182619199999996

In [16]:
sentence_meanings[0],sentence_meanings[1],sentence_meanings[2],sentence_meanings[3]

(tensor([-1.5256, -0.7502, -0.6540, -1.6095], grad_fn=<SelectBackward0>),
 tensor([-0.2092, -0.2013, -0.7509, -0.0189], grad_fn=<SelectBackward0>),
 tensor([ 0.9326, -0.2774,  0.3166, -1.6980], grad_fn=<SelectBackward0>),
 tensor([ 0.7698, -0.1935,  0.1223, -0.0585], grad_fn=<SelectBackward0>))

In [17]:
cs_0_0 = sentence_meanings[0][0]*sentence_meanings[0][0]+ sentence_meanings[0][1]*sentence_meanings[0][1]+ sentence_meanings[0][2]*sentence_meanings[0][2]+ sentence_meanings[0][3]*sentence_meanings[0][3]
cs_1_0 = sentence_meanings[1][0]*sentence_meanings[0][0]+ sentence_meanings[1][1]*sentence_meanings[0][1]+ sentence_meanings[1][2]*sentence_meanings[0][2]+ sentence_meanings[1][3]*sentence_meanings[0][3]
cs_2_0 = sentence_meanings[2][0]*sentence_meanings[0][0]+ sentence_meanings[2][1]*sentence_meanings[0][1]+ sentence_meanings[2][2]*sentence_meanings[0][2]+ sentence_meanings[2][3]*sentence_meanings[0][3]
cs_3_0 = sentence_meanings[3][0]*sentence_meanings[0][0]+ sentence_meanings[3][1]*sentence_meanings[0][1]+ sentence_meanings[3][2]*sentence_meanings[0][2]+ sentence_meanings[3][3]*sentence_meanings[0][3]

cs_0_0, cs_1_0, cs_2_0, cs_3_0

(tensor(5.9084, grad_fn=<AddBackward0>),
 tensor(0.9915, grad_fn=<AddBackward0>),
 tensor(1.3112, grad_fn=<AddBackward0>),
 tensor(-1.0151, grad_fn=<AddBackward0>))

In [ ]:
all_similarities = torch.zeros((sentence_meanings.shape[0], sentence_meanings.shape[0]))

for j in range(sentence_meanings.shape[0]):
   j_similarities= torch.zeros(sentence_meanings.shape[0])

   for i in range(sentence_meanings.shape[0]):
        for k in range(sentence_meanings.shape[1]):
         cs_j_i = sentence_meanings[j][k]*sentence_meanings[i][k] 
         j_similarities[i]= cs_j_i
         
   all_similarities[j]=j_similarities

all_similarities.detach().numpy()


array([[ 5.90842295e+00,  9.91524994e-01,  1.31123865e+00,
        -1.01506197e+00, -5.98358274e-01,  5.21510422e-01,
        -2.95679903e+00,  1.38435686e+00,  3.24948215e+00,
         1.05356288e+00, -7.98454523e-01, -3.48336786e-01,
         1.37064040e+00,  3.34363818e+00,  6.58395588e-01,
        -1.54289484e+00, -9.49555039e-01, -4.41114426e-01,
         1.03069091e+00, -3.94407916e+00],
       [ 9.91524994e-01,  6.48404419e-01, -3.44985247e-01,
        -2.12769225e-01, -8.34367275e-01, -3.59468281e-01,
        -4.32386786e-01,  6.17068112e-01,  9.22348142e-01,
         4.90614891e-01, -5.28138876e-01, -8.62775892e-02,
         2.12269612e-02,  9.08997953e-01,  5.62238276e-01,
        -9.59949076e-01, -4.58646148e-01, -6.07945442e-01,
        -1.72437117e-01, -8.67795944e-01],
       [ 1.31123865e+00, -3.44985247e-01,  3.93028903e+00,
         9.09577966e-01,  3.04722935e-01,  1.50815845e-02,
        -2.63633180e+00, -3.30206811e-01,  6.40884876e-01,
         6.56362772e-02,  9.7

In [23]:
all_similarities.shape

torch.Size([20, 20])

In [26]:
sentence_meanings.shape,sentence_meanings.T.shape

(torch.Size([20, 4]), torch.Size([4, 20]))

In [27]:
all_similarities = sentence_meanings @ sentence_meanings.T
all_similarities.detach().numpy()

all_similarities.shape

torch.Size([20, 20])

In [ ]:
attention_weights = all_similarities / torch.sum(all_similarities, dim=1, keepdim=True)